language: php
php:
  - '7.2'

jobs:
  include:
    - stage: build
      if: branch = master
      before_install:
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      - sudo apt-get update
      - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
      install:
      - composer install
      before_script:
      - phpenv config-rm xdebug.ini
      - pecl install rar
      - phpenv config-add rar.ini
      - phpenv config-add zip.ini
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t web-reader .
      - docker images
      - docker tag web-reader $DOCKER_USERNAME/web-reader
      - docker push $DOCKER_USERNAME/web-reader
